# Generated by Django 2.0.3 on 2018-04-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180418_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='seriesname',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='vote_average',
            field=models.CharField(default='unvoted', max_length=1000),
            preserve_default=False,
        ),
    ]
